<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />

<meta name="viewport" content="width=device-width, initial-scale=1" />



<title>Endogenous switching or sample selection models for count data</title>

<script>// Pandoc 2.9 adds attributes on both header and div. We remove the former (to
// be compatible with the behavior of Pandoc < 2.8).
document.addEventListener('DOMContentLoaded', function(e) {
  var hs = document.querySelectorAll("div.section[class*='level'] > :first-child");
  var i, h, a;
  for (i = 0; i < hs.length; i++) {
    h = hs[i];
    if (!/^h[1-6]$/i.test(h.tagName)) continue;  // it should be a header h1-h6
    a = h.attributes;
    while (a.length > 0) h.removeAttribute(a[0].name);
  }
});
</script>
<script>// Hide empty <a> tag within highlighted CodeBlock for screen reader accessibility (see https://github.com/jgm/pandoc/issues/6352#issuecomment-626106786) -->
// v0.0.1
// Written by JooYoung Seo (jooyoung@psu.edu) and Atsushi Yasumoto on June 1st, 2020.

document.addEventListener('DOMContentLoaded', function() {
  const codeList = document.getElementsByClassName("sourceCode");
  for (var i = 0; i < codeList.length; i++) {
    var linkList = codeList[i].getElementsByTagName('a');
    for (var j = 0; j < linkList.length; j++) {
      if (linkList[j].innerHTML === "") {
        linkList[j].setAttribute('aria-hidden', 'true');
      }
    }
  }
});
</script>
<script>$(document).ready(function(){
    if (typeof $('[data-toggle="tooltip"]').tooltip === 'function') {
        $('[data-toggle="tooltip"]').tooltip();
    }
    if ($('[data-toggle="popover"]').popover === 'function') {
        $('[data-toggle="popover"]').popover();
    }
});
</script>
<style type="text/css">
.lightable-minimal {
border-collapse: separate;
border-spacing: 16px 1px;
width: 100%;
margin-bottom: 10px;
}
.lightable-minimal td {
margin-left: 5px;
margin-right: 5px;
}
.lightable-minimal th {
margin-left: 5px;
margin-right: 5px;
}
.lightable-minimal thead tr:last-child th {
border-bottom: 2px solid #00000050;
empty-cells: hide;
}
.lightable-minimal tbody tr:first-child td {
padding-top: 0.5em;
}
.lightable-minimal.lightable-hover tbody tr:hover {
background-color: #f5f5f5;
}
.lightable-minimal.lightable-striped tbody tr:nth-child(even) {
background-color: #f5f5f5;
}
.lightable-classic {
border-top: 0.16em solid #111111;
border-bottom: 0.16em solid #111111;
width: 100%;
margin-bottom: 10px;
margin: 10px 5px;
}
.lightable-classic tfoot tr td {
border: 0;
}
.lightable-classic tfoot tr:first-child td {
border-top: 0.14em solid #111111;
}
.lightable-classic caption {
color: #222222;
}
.lightable-classic td {
padding-left: 5px;
padding-right: 5px;
color: #222222;
}
.lightable-classic th {
padding-left: 5px;
padding-right: 5px;
font-weight: normal;
color: #222222;
}
.lightable-classic thead tr:last-child th {
border-bottom: 0.10em solid #111111;
}
.lightable-classic.lightable-hover tbody tr:hover {
background-color: #F9EEC1;
}
.lightable-classic.lightable-striped tbody tr:nth-child(even) {
background-color: #f5f5f5;
}
.lightable-classic-2 {
border-top: 3px double #111111;
border-bottom: 3px double #111111;
width: 100%;
margin-bottom: 10px;
}
.lightable-classic-2 tfoot tr td {
border: 0;
}
.lightable-classic-2 tfoot tr:first-child td {
border-top: 3px double #111111;
}
.lightable-classic-2 caption {
color: #222222;
}
.lightable-classic-2 td {
padding-left: 5px;
padding-right: 5px;
color: #222222;
}
.lightable-classic-2 th {
padding-left: 5px;
padding-right: 5px;
font-weight: normal;
color: #222222;
}
.lightable-classic-2 tbody tr:last-child td {
border-bottom: 3px double #111111;
}
.lightable-classic-2 thead tr:last-child th {
border-bottom: 1px solid #111111;
}
.lightable-classic-2.lightable-hover tbody tr:hover {
background-color: #F9EEC1;
}
.lightable-classic-2.lightable-striped tbody tr:nth-child(even) {
background-color: #f5f5f5;
}
.lightable-material {
min-width: 100%;
white-space: nowrap;
table-layout: fixed;
font-family: Roboto, sans-serif;
border: 1px solid #EEE;
border-collapse: collapse;
margin-bottom: 10px;
}
.lightable-material tfoot tr td {
border: 0;
}
.lightable-material tfoot tr:first-child td {
border-top: 1px solid #EEE;
}
.lightable-material th {
height: 56px;
padding-left: 16px;
padding-right: 16px;
}
.lightable-material td {
height: 52px;
padding-left: 16px;
padding-right: 16px;
border-top: 1px solid #eeeeee;
}
.lightable-material.lightable-hover tbody tr:hover {
background-color: #f5f5f5;
}
.lightable-material.lightable-striped tbody tr:nth-child(even) {
background-color: #f5f5f5;
}
.lightable-material.lightable-striped tbody td {
border: 0;
}
.lightable-material.lightable-striped thead tr:last-child th {
border-bottom: 1px solid #ddd;
}
.lightable-material-dark {
min-width: 100%;
white-space: nowrap;
table-layout: fixed;
font-family: Roboto, sans-serif;
border: 1px solid #FFFFFF12;
border-collapse: collapse;
margin-bottom: 10px;
background-color: #363640;
}
.lightable-material-dark tfoot tr td {
border: 0;
}
.lightable-material-dark tfoot tr:first-child td {
border-top: 1px solid #FFFFFF12;
}
.lightable-material-dark th {
height: 56px;
padding-left: 16px;
padding-right: 16px;
color: #FFFFFF60;
}
.lightable-material-dark td {
height: 52px;
padding-left: 16px;
padding-right: 16px;
color: #FFFFFF;
border-top: 1px solid #FFFFFF12;
}
.lightable-material-dark.lightable-hover tbody tr:hover {
background-color: #FFFFFF12;
}
.lightable-material-dark.lightable-striped tbody tr:nth-child(even) {
background-color: #FFFFFF12;
}
.lightable-material-dark.lightable-striped tbody td {
border: 0;
}
.lightable-material-dark.lightable-striped thead tr:last-child th {
border-bottom: 1px solid #FFFFFF12;
}
.lightable-paper {
width: 100%;
margin-bottom: 10px;
color: #444;
}
.lightable-paper tfoot tr td {
border: 0;
}
.lightable-paper tfoot tr:first-child td {
border-top: 1px solid #00000020;
}
.lightable-paper thead tr:last-child th {
color: #666;
vertical-align: bottom;
border-bottom: 1px solid #00000020;
line-height: 1.15em;
padding: 10px 5px;
}
.lightable-paper td {
vertical-align: middle;
border-bottom: 1px solid #00000010;
line-height: 1.15em;
padding: 7px 5px;
}
.lightable-paper.lightable-hover tbody tr:hover {
background-color: #F9EEC1;
}
.lightable-paper.lightable-striped tbody tr:nth-child(even) {
background-color: #00000008;
}
.lightable-paper.lightable-striped tbody td {
border: 0;
}
</style>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>



<style type="text/css">
  code {
    white-space: pre;
  }
  .sourceCode {
    overflow: visible;
  }
</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    var j = 0;
    while (j < rules.length) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") {
        j++;
        continue;
      }
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') {
        j++;
        continue;
      }
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>




<style type="text/css">body {
background-color: #fff;
margin: 1em auto;
max-width: 700px;
overflow: visible;
padding-left: 2em;
padding-right: 2em;
font-family: "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;
font-size: 14px;
line-height: 1.35;
}
#TOC {
clear: both;
margin: 0 0 10px 10px;
padding: 4px;
width: 400px;
border: 1px solid #CCCCCC;
border-radius: 5px;
background-color: #f6f6f6;
font-size: 13px;
line-height: 1.3;
}
#TOC .toctitle {
font-weight: bold;
font-size: 15px;
margin-left: 5px;
}
#TOC ul {
padding-left: 40px;
margin-left: -1.5em;
margin-top: 5px;
margin-bottom: 5px;
}
#TOC ul ul {
margin-left: -2em;
}
#TOC li {
line-height: 16px;
}
table {
margin: 1em auto;
border-width: 1px;
border-color: #DDDDDD;
border-style: outset;
border-collapse: collapse;
}
table th {
border-width: 2px;
padding: 5px;
border-style: inset;
}
table td {
border-width: 1px;
border-style: inset;
line-height: 18px;
padding: 5px 5px;
}
table, table th, table td {
border-left-style: none;
border-right-style: none;
}
table thead, table tr.even {
background-color: #f7f7f7;
}
p {
margin: 0.5em 0;
}
blockquote {
background-color: #f6f6f6;
padding: 0.25em 0.75em;
}
hr {
border-style: solid;
border: none;
border-top: 1px solid #777;
margin: 28px 0;
}
dl {
margin-left: 0;
}
dl dd {
margin-bottom: 13px;
margin-left: 13px;
}
dl dt {
font-weight: bold;
}
ul {
margin-top: 0;
}
ul li {
list-style: circle outside;
}
ul ul {
margin-bottom: 0;
}
pre, code {
background-color: #f7f7f7;
border-radius: 3px;
color: #333;
white-space: pre-wrap; 
}
pre {
border-radius: 3px;
margin: 5px 0px 10px 0px;
padding: 10px;
}
pre:not([class]) {
background-color: #f7f7f7;
}
code {
font-family: Consolas, Monaco, 'Courier New', monospace;
font-size: 85%;
}
p > code, li > code {
padding: 2px 0px;
}
div.figure {
text-align: center;
}
img {
background-color: #FFFFFF;
padding: 2px;
border: 1px solid #DDDDDD;
border-radius: 3px;
border: 1px solid #CCCCCC;
margin: 0 5px;
}
h1 {
margin-top: 0;
font-size: 35px;
line-height: 40px;
}
h2 {
border-bottom: 4px solid #f7f7f7;
padding-top: 10px;
padding-bottom: 2px;
font-size: 145%;
}
h3 {
border-bottom: 2px solid #f7f7f7;
padding-top: 10px;
font-size: 120%;
}
h4 {
border-bottom: 1px solid #f7f7f7;
margin-left: 8px;
font-size: 105%;
}
h5, h6 {
border-bottom: 1px solid #ccc;
font-size: 105%;
}
a {
color: #0033dd;
text-decoration: none;
}
a:hover {
color: #6666ff; }
a:visited {
color: #800080; }
a:visited:hover {
color: #BB00BB; }
a[href^="http:"] {
text-decoration: underline; }
a[href^="https:"] {
text-decoration: underline; }

code > span.kw { color: #555; font-weight: bold; } 
code > span.dt { color: #902000; } 
code > span.dv { color: #40a070; } 
code > span.bn { color: #d14; } 
code > span.fl { color: #d14; } 
code > span.ch { color: #d14; } 
code > span.st { color: #d14; } 
code > span.co { color: #888888; font-style: italic; } 
code > span.ot { color: #007020; } 
code > span.al { color: #ff0000; font-weight: bold; } 
code > span.fu { color: #900; font-weight: bold; } 
code > span.er { color: #a61717; background-color: #e3d2d2; } 
</style>




</head>

<body>




<h1 class="title toc-ignore">Endogenous switching or sample selection models for count data</h1>



<div id="introduction" class="section level1">
<h1>Introduction</h1>
<p>In two seminal papers, <span class="citation">Heckman (1976)</span> and <span class="citation">Heckman (1979)</span> considered the case where two variable are jointly determined: a binomial variable and an outcome continuous variable. For example, the continuous variable can be the wage and the binomial variable the labor force participation. In this case, the wage is observed only for the sub-sample of the individuals who works. If the unobserved determinants of labor force participation are correlated with the unobserved determinants of wage, estimating the wage equation only on the subset of individuals who work will result in an inconsistent estimator. This case is called the <strong>sample selection</strong> model.</p>
<p>An other example is the case where the binomial variable is a a dummy for private vs public sector. In this case the wage is observed for the whole sample (for the individuals in the public and in the private sector). But, once again, if the unobserved determinants of the chosen sector are correlated with those of the wage, estimating the wage equation only will leads to inconsistent estimators. This case is called the <strong>endogenous switching</strong> model.</p>
<p>Two consistent method of estimation can be used in this context:</p>
<ul>
<li>the first one is a two-step method where, in a first step, a probit model for the binomial variable is estimated and, in a second step, the outcome equation is estimated by OLS with a supplementary covariate which is a function of the linear predictor of the probit<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a>,</li>
<li>the second one is the maximum likelihood estimation of the system of the two equations, assuming that the error terms are jointly normally distributed.</li>
</ul>
</div>
<div id="sample-selection-and-endogenous-switching-for-count-data" class="section level1">
<h1>Sample selection and endogenous switching for count data</h1>
<p>Let <span class="math inline">\(y\)</span> be a count response (for sake of simplicity a Poisson variable) and <span class="math inline">\(z\)</span> a binomial variable. The value of <span class="math inline">\(z\)</span> is given by the sign of <span class="math inline">\(\alpha ^ \top z + \nu\)</span>, where <span class="math inline">\(\nu\)</span> is a standard normal deviate, <span class="math inline">\(z\)</span> a vector of covariates and <span class="math inline">\(\alpha\)</span> the associated vector of unknown parameters. The distribution of <span class="math inline">\(y_n\)</span> is Poisson with parameter <span class="math inline">\(\lambda_n\)</span>, given by <span class="math inline">\(\ln \lambda_n = \beta ^ \top x_n + \epsilon_n\)</span> where <span class="math inline">\(x\)</span> is a second set of covariates (which can overlap with <span class="math inline">\(z\)</span>), <span class="math inline">\(\beta\)</span> is the corresponding set of unknown parameters and <span class="math inline">\(\epsilon\)</span> is a random normal deviate with 0 mean and a standard deviation equal to <span class="math inline">\(\sigma\)</span>. <span class="math inline">\(\epsilon\)</span> and <span class="math inline">\(\nu\)</span> being potentially correlated, their joint distribution has to be considered:</p>
<p><span class="math display">\[
f(\epsilon, \nu ; \sigma, \rho) = 
\frac{1}{2\pi\sqrt{1 - \rho ^ 2}\sigma}
e^{\displaystyle-\frac{1}{2} \frac{\left(\frac{\epsilon}{\sigma}\right) ^ 2 + \nu ^
2 - 2 \rho \left(\frac{\epsilon}{\sigma}\right)\nu}{1 - \rho ^2}}
= \frac{1}{\sqrt{2\pi}}\sigma e ^
{-\frac{1}{2}\left(\frac{\epsilon}{\sigma}\right) ^ 2}
\frac{1}{\sqrt{2\pi}\sqrt{1 - \rho ^ 2}}
e^{-\frac{1}{2}\left(\frac{(\nu - \rho \epsilon / \sigma)}{\sqrt{1 -
\rho ^ 2}}\right) ^ 2}
\]</span></p>
<p>The second expression classically gives the joint distribution as the product of the marginal distribution of <span class="math inline">\(\epsilon\)</span> and the conditional distribution of <span class="math inline">\(\nu\)</span>.</p>
<p>For <span class="math inline">\(z=1\)</span>, the unconditional distribution of <span class="math inline">\(y\)</span> is obtained by integrating out <span class="math inline">\(g(y_n \mid x_n, \epsilon_n, \nu_n, z_n = 1)\)</span> with respect with the two random deviates:</p>
<p><span class="math display">\[
P(y_n \mid x_n, z_n = 1) = \int_{-\infty} ^ {+\infty}\int_{-\alpha ^ \top
z_n} ^ {+ \infty} g(y_n \mid x_n, \epsilon_n, z_n = 1)
f(\epsilon, \nu) d\epsilon d\nu
\]</span></p>
<p><span class="math display">\[
P(y_n \mid x_n, z_n = 1) = \int_{-\infty} ^ {+\infty}
g(y_n \mid x_n, \epsilon_n, z_n = 1)
\left(\int_{-\alpha ^ \top z_n} ^ {+ \infty} 
\frac{1}{\sqrt{2\pi}\sqrt{1 - \rho ^ 2}}
e^{-\frac{1}{2}\left(\frac{(\nu - \rho \epsilon / \sigma)}{\sqrt{1 -
\rho ^ 2}}\right) ^ 2} 
d\nu\right)
\frac{1}{\sqrt{2\pi}\sigma} e ^
{-\frac{1}{2}\left(\frac{\epsilon}{\sigma}\right) ^ 2}
d\epsilon
\]</span></p>
<p>By symetry of the normal distribution, the term in braquet is:</p>
<p><span class="math display">\[
\Phi\left(\frac{\alpha ^ \top z_n + \rho / \sigma \epsilon}{\sqrt{1 -
\rho ^ 2}}\right)
\]</span></p>
<p>which is the probability that <span class="math inline">\(z = 1\)</span> for a given value of <span class="math inline">\(\epsilon\)</span>. The density of <span class="math inline">\(y\)</span> given that <span class="math inline">\(z = 1\)</span> is then:</p>
<p><span class="math display">\[\begin{equation}
P(y_n \mid x_n, z_n = 1) = \int_{-\infty} ^ {+\infty} \frac{e ^
{-\mbox{exp}(\beta ^ \top x_n + \epsilon_n)}e^{y_n(\beta^\top x_n +
\epsilon_n)}}{y_n!}\Phi\left(\frac{\alpha ^ \top z_n + \rho / \sigma \epsilon}{\sqrt{1 -
\rho ^ 2}}\right)\frac{1}{\sqrt{2\pi}\sigma} e ^
{-\frac{1}{2}\left(\frac{\epsilon}{\sigma}\right) ^ 2} d\epsilon
(\#eq:probyz1)
\end{equation}\]</span></p>
<p>By symmetry, it is easily shown that <span class="math inline">\(P(y_n \mid x_n, z_n = 0)\)</span> is similar except that <span class="math inline">\(\Phi\left( (\alpha ^ \top z_n + \rho / \sigma \epsilon) / \sqrt{1 - \rho ^ 2}\right)\)</span> is replaced by <span class="math inline">\(1 - \Phi\left( (\alpha ^ \top z_n + \rho / \sigma \epsilon) / \sqrt{1 - \rho ^ 2}\right) = \Phi\left( -(\alpha ^ \top z_n + \rho / \sigma \epsilon) / \sqrt{1 - \rho ^ 2}\right)\)</span>, so that a general formulation of the distribution of <span class="math inline">\(y\)</span> is, denoting <span class="math inline">\(q = 2 z -1\)</span>:</p>
<p><span class="math display">\[\begin{equation}
(\#eq:proby)
P(y_n \mid x_n) = \int_{-\infty} ^ {+\infty} \frac{e ^
{-\mbox{exp}(\beta ^ \top x_n + \epsilon_n)}e^{y_n(\beta^\top x_n +
\epsilon_n)}}{y_n!}\Phi\left(q_n\frac{\alpha ^ \top z_n + \rho / \sigma \epsilon}{\sqrt{1 -
\rho ^ 2}}\right)\frac{1}{\sqrt{2\pi}\sigma} e ^
{-\frac{1}{2}\left(\frac{\epsilon}{\sigma}\right) ^ 2} d\epsilon
\end{equation}\]</span></p>
<p>There is no closed form for this integral but, using the change of variable <span class="math inline">\(\eta = \epsilon / \sqrt{2} / \sigma\)</span>, we get:</p>
<p><span class="math display">\[
P(y_n \mid x_n) = \int_{-\infty} ^ {+\infty} \frac{e ^
{-\mbox{exp}(\beta ^ \top x_n + \sqrt{2} \sigma  \eta)}e^{y_n(\beta^\top x_n +
\sqrt{2}\sigma\eta)}}{y_n!}\Phi\left(q_n\frac{\alpha ^ \top z_n + \sqrt{2} \rho  \eta}{\sqrt{1 -
\rho ^ 2}}\right)\frac{1}{\sqrt{\pi}} e ^
{-\eta ^ 2} d\eta
\]</span></p>
<p>which can be approximated using Gauss-Hermite quadrature. Denting <span class="math inline">\(\eta_r\)</span> the nodes and <span class="math inline">\(\omega_r\)</span> the weights:</p>
<p><span class="math display">\[
P(y_n \mid x_n) \approx 
\sum_{r = 1} ^ R
\omega_r \frac{e ^
{-\mbox{exp}(\beta ^ \top x_n + \sqrt{2} \sigma  \eta_r)}e^{y_n(\beta^\top x_n +
\sqrt{2}\sigma\eta_r)}}{y_n!}\Phi\left(q_n\frac{\alpha ^ \top z_n + \sqrt{2} \rho  \eta_r}{\sqrt{1 -
\rho ^ 2}}\right)\frac{1}{\sqrt{\pi}} e ^
{-\eta_r ^ 2}
\]</span></p>
<p>For the exogenous switching model, the contribution of one observation to the likelihood is given by @ref(eq:proby).</p>
<p>For the sample selection model, the contribution of one observation to the likelihood is given by @ref(eq:probyz1) if <span class="math inline">\(z_n = 1\)</span>. If <span class="math inline">\(z_n = 0\)</span>, <span class="math inline">\(y\)</span> is unobserved and the contribution of such observations to the likelihood is the probability that <span class="math inline">\(z_n = 0\)</span>, which is:</p>
<p><span class="math display">\[\begin{equation}
P(z_n = 0 \mid x_n) = \int_{-\infty} ^ {+\infty}
\Phi\left(q_n\frac{\alpha ^ \top z_n + \rho / \sigma \epsilon}{\sqrt{1 -
\rho ^ 2}}\right)\frac{1}{\sqrt{2\pi}\sigma} e ^
{-\frac{1}{2}\left(\frac{\epsilon}{\sigma}\right) ^ 2} d\epsilon
\end{equation}\]</span></p>
<p>The ML estimator is computing intensive as the integral has no closed form. One alternative is to use non-linear least squares, by first computing the expectation of <span class="math inline">\(y\)</span>. <span class="citation">Terza (1998)</span> showed that, in the endogenous switching case:</p>
<p><span class="math display">\[
\mbox{E}(y_n\mid x_n) = \mbox{exp}\left(\beta ^ \top x_n + \ln \frac{\Phi\left(q_n(\alpha ^\top
z_n + \theta)\right)}{\Phi\left(q_n(\alpha ^\top z_n)\right)}\right)
\]</span></p>
<p>For the sample selection case, we have:</p>
<p><span class="math display">\[
\mbox{E}(y_n\mid x_n, z_n = 1) = \mbox{exp}\left(\beta ^\top x_n + \ln \frac{\Phi(\alpha ^\top
z_n + \theta)}{\Phi(\alpha ^ \top z_n)}\right)
\]</span></p>
<p><span class="citation">Greene (2001)</span> noted that, taking a first order Taylor series of <span class="math inline">\(\ln \frac{\Phi(\alpha ^\top z_n + \theta)}{\Phi(\alpha ^ \top z_n)}\)</span> around <span class="math inline">\(\theta = 0\)</span> gives: <span class="math inline">\(\theta \phi(\alpha ^ \top z_n) / \Phi(\alpha ^ \top z_n)\)</span>, which is the inverse mills ratio that is used in the linear case in order to correct the inconsistency due to sample selection. As <span class="math inline">\(\alpha\)</span> can be consistently estimated by a probit model, the NLS estimator is obtained by minimizing with respect to <span class="math inline">\(\beta\)</span> and <span class="math inline">\(\theta\)</span> the sum of squares of the following residuals:</p>
<p><span class="math display">\[
y_n - e^{\displaystyle \beta ^ \top x_n + \ln
\frac{\Phi(\hat{\alpha} ^ \top z_n + \theta)}{\Phi(\hat{\alpha}
^ \top z_n)}}
\]</span></p>
<p>As it is customary for these two-steps estimator, the covariance matrix of the estimators should take into account the fact that <span class="math inline">\(\alpha\)</span> has been estimated in the first step. Moreover, only <span class="math inline">\(\theta = \rho \sigma\)</span> is estimated. To retrieve an estimator of <span class="math inline">\(\sigma\)</span>, <span class="citation">Terza (1998)</span> proposed to insert into the log-likelihood function the estimated values of <span class="math inline">\(\alpha\)</span>, <span class="math inline">\(\beta\)</span> and <span class="math inline">\(\theta\)</span> and then to maximize it with respect to <span class="math inline">\(\sigma\)</span><a href="#fn2" class="footnote-ref" id="fnref2"><sup>2</sup></a>.</p>
</div>
<div id="the-escount-function" class="section level1">
<h1>The <code>escount</code> function</h1>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true"></a><span class="kw">library</span>(<span class="st">&quot;micsr&quot;</span>)</span></code></pre></div>
<p>The <code>escount</code> function estimates the endogenous switching and the sample selection model for count data. The first one is obtained by setting the <code>model</code> argument to <code>&#39;es&#39;</code> (the default) and the second one to <code>&#39;ss&#39;</code>. The estimation method is selected using the <code>method</code> argument, which can be either <code>&#39;twosteps&#39;</code> for the two-steps non-linear least squares model (the default) or <code>&#39;ML&#39;</code> for maximum likelihood. The model is described by an extended formula (using the <strong>Formula</strong> package) of the form:</p>
<p><code>y | d ~ x + y + z + d | x + y + w</code></p>
<p>which indicates that the two responses are <code>y</code> (the count) and <code>d</code> (the binomial variable), that the covariates are <code>x</code>, <code>y</code> and <code>z</code> for the count equation and <code>x</code>, <code>y</code> and <code>w</code> for the switching/selection equation. When there are two large sets of covariates that overlap, it is possible to define the second set of covariates by updating the first one:</p>
<p><code>y | d ~ x + y + z + d | . - d - z + w</code></p>
<p><code>R</code> is an integer that indicates the number of points used for the Gauss-Hermite quadrature method. Relevant only for the ML method, the <code>hessian</code> argument is a boolean: if <code>TRUE</code>, the covariance matrix of the coefficients is estimated using the numerical hessian, which is computed using the <code>hessian</code> function of the <strong>numDeriv</strong> package, otherwise, the outer product of the gradient is used.</p>
<p><code>escount</code> returns an object of class <code>escount</code> which inherits from <code>lm</code>.</p>
<!-- This is a list that contains usual items that can be found in -->
<!-- `lm` objects and some more specific items: -->
<!-- - `K` and `L` are the number of covariates in the count equation and -->
<!--   in the binomial equation, -->
<!-- - `sigma` and `rho` are the estimates of $\sigma$ and $\rho$ for the -->
<!--   two-steps method. -->
</div>
<div id="trips-demand" class="section level1">
<h1>Trips demand</h1>
<p><span class="citation">Terza (1998)</span> analyzed the number of trips taken by 577 individuals in the United States in 1978 the day before they were interviewed. The <code>trips</code> data set is included in the <strong>micsr</strong> package.A major determinant of trips demand is the availability of a car in the household. <span class="citation">Terza (1998)</span> advocates that the unobserved determinants of the decision of having a car may be correlated with those of the trip demand equation. In this case the estimation of the Poisson model will lead to inconsistent estimators. The covariates are the share of trips for work or school (<code>workschl</code>), the number of individuals in the household (<code>size</code>), the distance to the central business district (<code>dist</code>) a factor (<code>smsa</code>) with two levels for small and large urban area, the number of full-time worker in household (<code>fulltime</code>), the distance from home to nearest transit node, household income divided by the median income of the census tract (<code>realinc</code>), a dummy if the survey period is Saturday or Sunday (<code>weeekend</code>) and a dummy for owning at least a car (<code>car</code>). Although the coefficients are identified, as in the classic Heckman model by the non-linearity of the correction term, <span class="citation">Terza (1998)</span> use a different set of variable for the binomial and the count parts of the model. Namely, the <code>weekend</code> covariate is removed and <code>adults</code> is added in the binomial part of the model.</p>
<p>We first compute the two-steps NLS estimator. The <code>model</code> and <code>method</code> arguments needn’t to be set are the default values are <code>es</code> (endogenous switching) and <code>twosteps</code> (two-steps NLS).</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true"></a>trips_2s &lt;-<span class="st"> </span><span class="kw">escount</span>(trips <span class="op">|</span><span class="st"> </span>car <span class="op">~</span><span class="st"> </span>workschl <span class="op">+</span><span class="st"> </span>size <span class="op">+</span><span class="st"> </span>dist <span class="op">+</span><span class="st"> </span>smsa <span class="op">+</span><span class="st"> </span>fulltime <span class="op">+</span><span class="st"> </span>distnod <span class="op">+</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true"></a><span class="st">                        </span>realinc <span class="op">+</span><span class="st"> </span>weekend <span class="op">+</span><span class="st"> </span>car <span class="op">|</span><span class="st"> </span>. <span class="op">-</span><span class="st"> </span>car <span class="op">-</span><span class="st"> </span>weekend <span class="op">+</span><span class="st"> </span>adults,</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true"></a>                    <span class="dt">data =</span> trips)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true"></a><span class="kw">names</span>(trips_2s)</span></code></pre></div>
<pre><code>##  [1] &quot;coefficients&quot;  &quot;sigma&quot;         &quot;rho&quot;           &quot;vcov&quot;         
##  [5] &quot;residuals&quot;     &quot;fitted.values&quot; &quot;model&quot;         &quot;terms&quot;        
##  [9] &quot;value&quot;         &quot;npar&quot;          &quot;df.residual&quot;   &quot;xlevels&quot;      
## [13] &quot;na.action&quot;     &quot;call&quot;          &quot;first&quot;         &quot;est_method&quot;</code></pre>
<p>The result is a list with usual items, except <!-- `L` and `K` which are --> <!-- the number of the covariates in the binomial and in the count --> <!-- equations,  --> <code>sigma</code> and <code>rho</code> which are the estimates of <span class="math inline">\(\sigma\)</span> and <span class="math inline">\(\rho\)</span> obtained from the estimation of <span class="math inline">\(\theta\)</span>.</p>
<p>The print of the summary method returns the usual table of coefficients, the value of the objective function (the sum of squares residuals) and the estimated values of <span class="math inline">\(\sigma\)</span> and <span class="math inline">\(\rho\)</span>:</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true"></a><span class="kw">summary</span>(trips_2s)</span></code></pre></div>
<pre><code>## Two-steps estimation
##               Estimate Std. Error z-value  Pr(&gt;|z|)    
## (Intercept) -1.4455570  0.4139240 -3.4923 0.0004788 ***
## workschl    -0.5543755  0.1472626 -3.7645 0.0001669 ***
## size         0.1487720  0.0302495  4.9182 8.736e-07 ***
## dist        -0.0089621  0.0056417 -1.5886 0.1121584    
## smsa        -0.0088507  0.1014225 -0.0873 0.9304600    
## fulltime     0.1059545  0.0740731  1.4304 0.1526007    
## distnod      0.0043303  0.0025689  1.6856 0.0918674 .  
## realinc      0.0066861  0.0178072  0.3755 0.7073078    
## weekend     -0.1650841  0.1152872 -1.4319 0.1521617    
## car          2.7957446  0.4209103  6.6421 3.092e-11 ***
## theta       -0.5662482  0.2221207 -2.5493 0.0107945 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## deviance: NULL
## 
## Estimated value of sigma: 0.71951
## Implied value for rho   : -0.78699</code></pre>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true"></a>trips_pois &lt;-<span class="st"> </span><span class="kw">glm</span>(trips <span class="op">~</span><span class="st"> </span>workschl <span class="op">+</span><span class="st"> </span>size <span class="op">+</span><span class="st"> </span>dist <span class="op">+</span><span class="st"> </span>smsa <span class="op">+</span><span class="st"> </span>fulltime <span class="op">+</span><span class="st"> </span>distnod <span class="op">+</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true"></a><span class="st">                      </span>realinc <span class="op">+</span><span class="st"> </span>weekend <span class="op">+</span><span class="st"> </span>car, <span class="dt">data =</span> trips, <span class="dt">family =</span> poisson)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true"></a>trips_ml &lt;-<span class="st"> </span><span class="kw">update</span>(trips_2s, <span class="dt">method =</span> <span class="st">&quot;ml&quot;</span>)</span></code></pre></div>
<p>The following table presents the results of a Poisson estimation and of the endogenous switching model, estimated by the two-steps non-linear least squares method and by maximum likelihood.</p>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
Estimation results for the trip demand model
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:center;">
Poisson
</th>
<th style="text-align:center;">
 2 steps
</th>
<th style="text-align:center;">
ML
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:center;">
−0.570
</td>
<td style="text-align:center;">
−1.446
</td>
<td style="text-align:center;">
−1.413
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:center;">
(0.125)
</td>
<td style="text-align:center;">
(0.414)
</td>
<td style="text-align:center;">
(0.193)
</td>
</tr>
<tr>
<td style="text-align:left;">
workschl
</td>
<td style="text-align:center;">
−0.456
</td>
<td style="text-align:center;">
−0.554
</td>
<td style="text-align:center;">
−0.349
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:center;">
(0.070)
</td>
<td style="text-align:center;">
(0.147)
</td>
<td style="text-align:center;">
(0.131)
</td>
</tr>
<tr>
<td style="text-align:left;">
size
</td>
<td style="text-align:center;">
0.167
</td>
<td style="text-align:center;">
0.149
</td>
<td style="text-align:center;">
0.156
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:center;">
(0.012)
</td>
<td style="text-align:center;">
(0.030)
</td>
<td style="text-align:center;">
(0.024)
</td>
</tr>
<tr>
<td style="text-align:left;">
dist
</td>
<td style="text-align:center;">
−0.002
</td>
<td style="text-align:center;">
−0.009
</td>
<td style="text-align:center;">
−0.003
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:center;">
(0.001)
</td>
<td style="text-align:center;">
(0.006)
</td>
<td style="text-align:center;">
(0.003)
</td>
</tr>
<tr>
<td style="text-align:left;">
smsa
</td>
<td style="text-align:center;">
−0.031
</td>
<td style="text-align:center;">
−0.009
</td>
<td style="text-align:center;">
0.017
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:center;">
(0.044)
</td>
<td style="text-align:center;">
(0.101)
</td>
<td style="text-align:center;">
(0.085)
</td>
</tr>
<tr>
<td style="text-align:left;">
fulltime
</td>
<td style="text-align:center;">
0.248
</td>
<td style="text-align:center;">
0.106
</td>
<td style="text-align:center;">
0.249
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:center;">
(0.026)
</td>
<td style="text-align:center;">
(0.074)
</td>
<td style="text-align:center;">
(0.057)
</td>
</tr>
<tr>
<td style="text-align:left;">
distnod
</td>
<td style="text-align:center;">
0.005
</td>
<td style="text-align:center;">
0.004
</td>
<td style="text-align:center;">
0.005
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:center;">
(0.001)
</td>
<td style="text-align:center;">
(0.003)
</td>
<td style="text-align:center;">
(0.002)
</td>
</tr>
<tr>
<td style="text-align:left;">
realinc
</td>
<td style="text-align:center;">
0.019
</td>
<td style="text-align:center;">
0.007
</td>
<td style="text-align:center;">
0.004
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:center;">
(0.006)
</td>
<td style="text-align:center;">
(0.018)
</td>
<td style="text-align:center;">
(0.011)
</td>
</tr>
<tr>
<td style="text-align:left;">
weekend
</td>
<td style="text-align:center;">
−0.074
</td>
<td style="text-align:center;">
−0.165
</td>
<td style="text-align:center;">
−0.100
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:center;">
(0.049)
</td>
<td style="text-align:center;">
(0.115)
</td>
<td style="text-align:center;">
(0.089)
</td>
</tr>
<tr>
<td style="text-align:left;">
car
</td>
<td style="text-align:center;">
1.413
</td>
<td style="text-align:center;">
2.796
</td>
<td style="text-align:center;">
2.166
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:center;">
(0.123)
</td>
<td style="text-align:center;">
(0.421)
</td>
<td style="text-align:center;">
(0.231)
</td>
</tr>
<tr>
<td style="text-align:left;">
theta
</td>
<td style="text-align:center;">
</td>
<td style="text-align:center;">
−0.566
</td>
<td style="text-align:center;">
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:center;">
</td>
<td style="text-align:center;">
(0.222)
</td>
<td style="text-align:center;">
</td>
</tr>
<tr>
<td style="text-align:left;">
sigma
</td>
<td style="text-align:center;">
</td>
<td style="text-align:center;">
</td>
<td style="text-align:center;">
0.737
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:center;">
</td>
<td style="text-align:center;">
</td>
<td style="text-align:center;">
(0.038)
</td>
</tr>
<tr>
<td style="text-align:left;">
rho
</td>
<td style="text-align:center;">
</td>
<td style="text-align:center;">
</td>
<td style="text-align:center;">
−0.767
</td>
</tr>
<tr>
<td style="text-align:left;box-shadow: 0px 1.5px">
</td>
<td style="text-align:center;box-shadow: 0px 1.5px">
</td>
<td style="text-align:center;box-shadow: 0px 1.5px">
</td>
<td style="text-align:center;box-shadow: 0px 1.5px">
(0.133)
</td>
</tr>
<tr>
<td style="text-align:left;">
Num.Obs.
</td>
<td style="text-align:center;">
577
</td>
<td style="text-align:center;">
577
</td>
<td style="text-align:center;">
577
</td>
</tr>
<tr>
<td style="text-align:left;">
AIC
</td>
<td style="text-align:center;">
3340.9
</td>
<td style="text-align:center;">
</td>
<td style="text-align:center;">
3121.5
</td>
</tr>
<tr>
<td style="text-align:left;">
BIC
</td>
<td style="text-align:center;">
3384.5
</td>
<td style="text-align:center;">
</td>
<td style="text-align:center;">
3213.0
</td>
</tr>
<tr>
<td style="text-align:left;">
Log.Lik.
</td>
<td style="text-align:center;">
−1660.440
</td>
<td style="text-align:center;">
</td>
<td style="text-align:center;">
−1539.726
</td>
</tr>
<tr>
<td style="text-align:left;">
F
</td>
<td style="text-align:center;">
82.194
</td>
<td style="text-align:center;">
</td>
<td style="text-align:center;">
</td>
</tr>
<tr>
<td style="text-align:left;">
RMSE
</td>
<td style="text-align:center;">
4.20
</td>
<td style="text-align:center;">
</td>
<td style="text-align:center;">
</td>
</tr>
</tbody>
</table>
<p>The coefficient of <code>car</code> is equal to 1.413 for the Poisson model, which implies that the number of trips increases by <span class="math inline">\(e^{1.413} - 1 = 311\)</span>% for individuals who belongs to households that own at least one car. The coefficient is much higher in the selection models (2.796 for the 2-step estimator and 2.160 for the ML estimator), which implies an increase of 767% for the ML estimator. The Poisson estimator is therefore downward biased, which indicates a negative correlation between the unobserved part of the trips demand equation and the propensity to own a car equation.</p>
</div>
<div id="physician-advice-and-alcohol-consumption" class="section level1">
<h1>Physician advice and alcohol consumption</h1>
<p><span class="citation">Kenkel and Terza (2001)</span> investigate the effect of physician’s advice on alcohol consumption. The outcome variable <code>drinks</code> is the number of drinks in the past 2 weeks and the selection variable <code>advice</code> is a dummy based on the respondents’ answer to the question “Have you ever been told by a physician to drink less”. The unobserved part of the equation indicating the propensity to receive an advice form the physician can obviously be correlated with the one of the alcohol consumption equation. The data set <code>drinks</code> is part of the **micsr package. The covariates are monthly income in thousands of dollars (<code>income</code>), <code>age</code> (a factor with six 10 years categories of age), education in years (<code>educ</code>), <code>race</code> (a factor with levels <code>white</code>, <code>black</code> and <code>other</code>), the marital status (<code>marital</code>, a factor with levels <code>single</code>, <code>married</code>, <code>widow</code>, <code>separated</code>), the employment status (a factor <code>empstatus</code> with levels <code>other</code>, <code>emp</code> and <code>unemp</code>) and the region (<code>region</code>, a factor with levels <code>west</code>, <code>northeast</code>, <code>midwest</code> and <code>south</code>). For the binomial part of the model, the same covariates are used (except of course <code>advice</code>) and 10 supplementary covariates indicating the insurance coverage and the health status are added.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true"></a>kt_pois &lt;-<span class="st"> </span><span class="kw">glm</span>(drinks <span class="op">~</span><span class="st"> </span>advice <span class="op">+</span><span class="st"> </span>income <span class="op">+</span><span class="st"> </span>age <span class="op">+</span><span class="st"> </span>educ <span class="op">+</span><span class="st"> </span>race <span class="op">+</span><span class="st"> </span>marital <span class="op">+</span><span class="st"> </span>empstatus <span class="op">+</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true"></a><span class="st">                   </span>region, <span class="dt">data =</span> drinks, <span class="dt">family =</span> poisson)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true"></a>kt_ml &lt;-<span class="st"> </span><span class="kw">escount</span>(drinks <span class="op">|</span><span class="st"> </span>advice <span class="op">~</span><span class="st"> </span>advice <span class="op">+</span><span class="st"> </span>income <span class="op">+</span><span class="st"> </span>age <span class="op">+</span><span class="st"> </span>educ <span class="op">+</span><span class="st"> </span>race <span class="op">+</span><span class="st"> </span>marital <span class="op">+</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true"></a><span class="st">                     </span>empstatus <span class="op">+</span><span class="st"> </span>region <span class="op">|</span><span class="st"> </span>income <span class="op">+</span><span class="st"> </span>age <span class="op">+</span><span class="st"> </span>educ <span class="op">+</span><span class="st"> </span>race <span class="op">+</span><span class="st"> </span>marital <span class="op">+</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true"></a><span class="st">                     </span>empstatus <span class="op">+</span><span class="st"> </span>region <span class="op">+</span><span class="st"> </span>medicare <span class="op">+</span><span class="st"> </span>medicaid <span class="op">+</span><span class="st"> </span>champus <span class="op">+</span><span class="st"> </span>hlthins <span class="op">+</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true"></a><span class="st">                     </span>regmed <span class="op">+</span><span class="st"> </span>dri <span class="op">+</span><span class="st"> </span>limits <span class="op">+</span><span class="st"> </span>diabete <span class="op">+</span><span class="st"> </span>hearthcond <span class="op">+</span><span class="st"> </span>stroke,</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true"></a>                 <span class="dt">data =</span> drinks, <span class="dt">method =</span> <span class="st">&quot;ml&quot;</span>)</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true"></a>kt_2s &lt;-<span class="st"> </span><span class="kw">update</span>(kt_ml, <span class="dt">method =</span> <span class="st">&quot;twosteps&quot;</span>)</span></code></pre></div>
<p>The following table presents the results of a Poisson estimation and of the endogenous switching model, estimated by the two-steps non-linear least squares method and maximum likelihood<a href="#fn3" class="footnote-ref" id="fnref3"><sup>3</sup></a>.</p>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
Poisson and endogenous switching models for alcohol demand
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:center;">
Poisson
</th>
<th style="text-align:center;">
 2 steps
</th>
<th style="text-align:center;">
ML
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:center;">
3.082
</td>
<td style="text-align:center;">
4.256
</td>
<td style="text-align:center;">
3.376
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:center;">
(0.034)
</td>
<td style="text-align:center;">
(0.300)
</td>
<td style="text-align:center;">
(0.048)
</td>
</tr>
<tr>
<td style="text-align:left;">
advice
</td>
<td style="text-align:center;">
0.477
</td>
<td style="text-align:center;">
−1.400
</td>
<td style="text-align:center;">
−0.848
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:center;">
(0.011)
</td>
<td style="text-align:center;">
(0.338)
</td>
<td style="text-align:center;">
(0.022)
</td>
</tr>
<tr>
<td style="text-align:left;">
income
</td>
<td style="text-align:center;">
0.003
</td>
<td style="text-align:center;">
0.001
</td>
<td style="text-align:center;">
0.009
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:center;">
(0.001)
</td>
<td style="text-align:center;">
(0.003)
</td>
<td style="text-align:center;">
(0.001)
</td>
</tr>
<tr>
<td style="text-align:left;">
educ
</td>
<td style="text-align:center;">
−0.026
</td>
<td style="text-align:center;">
−0.061
</td>
<td style="text-align:center;">
−0.055
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:center;">
(0.002)
</td>
<td style="text-align:center;">
(0.012)
</td>
<td style="text-align:center;">
(0.003)
</td>
</tr>
<tr>
<td style="text-align:left;">
raceblack
</td>
<td style="text-align:center;">
−0.402
</td>
<td style="text-align:center;">
−0.258
</td>
<td style="text-align:center;">
−0.543
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:center;">
(0.017)
</td>
<td style="text-align:center;">
(0.117)
</td>
<td style="text-align:center;">
(0.025)
</td>
</tr>
<tr>
<td style="text-align:left;">
raceother
</td>
<td style="text-align:center;">
−0.527
</td>
<td style="text-align:center;">
−0.310
</td>
<td style="text-align:center;">
−0.593
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:center;">
(0.049)
</td>
<td style="text-align:center;">
(0.290)
</td>
<td style="text-align:center;">
(0.110)
</td>
</tr>
<tr>
<td style="text-align:left;">
theta
</td>
<td style="text-align:center;">
</td>
<td style="text-align:center;">
1.142
</td>
<td style="text-align:center;">
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:center;">
</td>
<td style="text-align:center;">
(0.319)
</td>
<td style="text-align:center;">
</td>
</tr>
<tr>
<td style="text-align:left;">
sigma
</td>
<td style="text-align:center;">
</td>
<td style="text-align:center;">
</td>
<td style="text-align:center;">
1.298
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:center;">
</td>
<td style="text-align:center;">
</td>
<td style="text-align:center;">
(0.011)
</td>
</tr>
<tr>
<td style="text-align:left;">
rho
</td>
<td style="text-align:center;">
</td>
<td style="text-align:center;">
</td>
<td style="text-align:center;">
0.463
</td>
</tr>
<tr>
<td style="text-align:left;box-shadow: 0px 1.5px">
</td>
<td style="text-align:center;box-shadow: 0px 1.5px">
</td>
<td style="text-align:center;box-shadow: 0px 1.5px">
</td>
<td style="text-align:center;box-shadow: 0px 1.5px">
(0.022)
</td>
</tr>
<tr>
<td style="text-align:left;">
Num.Obs.
</td>
<td style="text-align:center;">
2467
</td>
<td style="text-align:center;">
2467
</td>
<td style="text-align:center;">
2467
</td>
</tr>
<tr>
<td style="text-align:left;">
F
</td>
<td style="text-align:center;">
229.655
</td>
<td style="text-align:center;">
</td>
<td style="text-align:center;">
</td>
</tr>
<tr>
<td style="text-align:left;">
RMSE
</td>
<td style="text-align:center;">
22.16
</td>
<td style="text-align:center;">
</td>
<td style="text-align:center;">
</td>
</tr>
</tbody>
</table>
<p>The coefficient of <code>advice</code> in the alcohol demand equation is positive in the Poisson model, which would imply that a positive effect of physical advice on alcohol consumption. The estimation of the endogenous switching model shows that this positive coefficient is due to the positive correlation between the error terms of the two equations (the unobserved propensities to drink and to receive an advice from a physician are positively correlated).</p>
<!-- # Job changes -->
<!-- @WYSZ:MARR:18 analyzed the determinants of the number of job -->
<!-- changes. The data set `soep` (included in the **escount** package) is -->
<!-- an extract of the German Socio-Economic Panel survey of 1984. It -->
<!-- concerns 2651 individuals and the response `djc` is the number of -->
<!-- direct job changes (changes without an intervening spell of -->
<!-- unemployment). Obviously this variable is observed only for -->
<!-- individuals who are part of the job market, which corresponds to a -->
<!-- value equal to 1 for the selection variable `lfp`. The covariates for -->
<!-- the count equation are `spd` (a factor indicating if the individual is -->
<!-- a strong or a very strong supporter of the social-democrat party in -->
<!-- Germany), `whitecol` (a factor indicating it the individual is a white -->
<!-- collar) and `educ` (number of years of education). For the selection -->
<!-- equation, the covariates are `single` (a factor indicating if the -->
<!-- individual is single), `whitecol` and `exper` (full-time employment in -->
<!-- years). The results are presented in table \@ref(tab:soepres). -->
<!-- ```{r soepest, warning = FALSE, cache = TRUE} -->
<!-- soep_pois <- glm(djc ~ spd + whitecol + educ, data = soep, family = poisson) -->
<!-- soep_2s <- escount(djc | lfp ~ spd + whitecol + educ | single + whitecol + exper, -->
<!--                    data = soep, model = "ss") -->
<!-- soep_ml <- update(soep_2s, method = "ml") -->
<!-- ``` -->
<!-- ```{r soepres, warning = FALSE, eval = FALSE} -->
<!-- msummary(list("Poisson" = soep_pois, "2 steps" = soep_2s, "ML" = soep_ml), -->
<!-- #         gof_omit = "AIC|BIC|Log.Lik.", -->
<!--          label = "tab:soepres", -->
<!--          title = "Poisson and selection models for the job change model") -->
<!-- ``` -->
</div>
<div id="references" class="section level1 unnumbered">
<h1 class="unnumbered">References</h1>
<div id="refs" class="references hanging-indent">
<div id="ref-GREE:01">
<p>Greene, William H. 2001. “Fiml Estimation of Sample Selection Models for Count Data.” In <em>Economic Theory, Dynamics and Markets: Essays in Honor of Ryuzo Sato</em>, edited by Takashi Negishi, Rama V. Ramachandran, and Kazuo Mino, 73–91. Boston, MA: Springer US.</p>
</div>
<div id="ref-HECK:76">
<p>Heckman, James J. 1976. “The Common Structure of Statistical Models of Truncation, Sample Selection and Limited Dependent Variables and a Simple Estimator for Such Models.” <em>Annals of Economic and Social Measurement, Volume 5, Number 4</em>, 475–92.</p>
</div>
<div id="ref-HECK:79">
<p>———. 1979. “Sample Selection Bias as a Specification Error.” <em>Econometrica</em> 47 (1): 153–61.</p>
</div>
<div id="ref-KENK:TERZ:01">
<p>Kenkel, Donald S., and Joseph V. Terza. 2001. “The Effect of Physician Advice on Alcohol Consumption: Count Regression with an Endogenous Treatment Effect.” <em>Journal of Applied Econometrics</em> 16 (2): 165–84.</p>
</div>
<div id="ref-TERZ:98">
<p>Terza, Joseph V. 1998. “Estimating Count Data Models with Endogenous Switching: Sample Selection and Endogenous Treatment Effects.” <em>Journal of Econometrics</em> 84 (1): 129–54.</p>
</div>
</div>
</div>
<div class="footnotes">
<hr />
<ol>
<li id="fn1"><p>More precisely the inverse Mills ratio.<a href="#fnref1" class="footnote-back">↩︎</a></p></li>
<li id="fn2"><p>These once again requires to use Gauss-Hermite quadrature, but the problem is considerably simpler as the likelihood is maximized with respect with only one parameter.<a href="#fnref2" class="footnote-back">↩︎</a></p></li>
<li id="fn3"><p>The coefficients of <code>marital</code>, <code>empstatus</code> and <code>region</code> are omitted to save place.<a href="#fnref3" class="footnote-back">↩︎</a></p></li>
</ol>
</div>



<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
